### ISSUE TITLE
libraries for classpath

### ISSUE THREAD

**Issue by RavMazurek** [fkorotkov/gradle-libraries-plugin#4]
Hi, thanks for this amazing plugin :)

Is there any way to also use libraries[name] for buildscript->dependencies->classpath?

So basically im asking - can i use this plugin for itself? :)

**Comment by fkorotkov** [comment]
It's kind of possible for multi-projects builds. In my case, root `build.gradle` contains:

```groovy
buildscript {
  repositories {
    mavenLocal()
    jcenter()
  }
  dependencies {
    classpath 'com.fkorotkov:gradle-libraries-plugin:0.1'
  }
}

subprojects {
  apply plugin: 'com.fkorotkov.libraries'
}
```

After that, in some sub-module's `build.gradle` I can do things like:

```groovy
apply plugin: "com.google.protobuf"

buildscript {
  dependencies {
    classpath libraries['com.google.protobuf:protobuf-gradle-plugin']
  }
}
```

@RavMazurek, does it work for you?
