### ISSUE TITLE
Does this plugin do anything besides reinvent the wheel?

### ISSUE THREAD

**Issue by jawaff** [fkorotkov/gradle-libraries-plugin#6]
"This plugin allows to specify versions of external libraries in a centralized place and use them across the project"

There's a simple solution for declaring dependencies in multi-module Gradle projects. 

rootProject/build.gradle:
```
allprojects {
  dependencies {
    implementation '<group>:<name>:<version>'
  }
}
```

There's also a simple solution for doing that across potentially hundreds of projects. You just have to create a Maven BOM, which is something that's completely standard and used by many libraries (e.g. spring, jersey, jetty, etc). Since Gradle 4.6, I believe we have BOM support and there's a spring-dependency-management plugin that does something similar.

You are relying on that one version plugin and I think that's pretty cool. Gradle doesn't have an easy way to check for latest dependency versions and update them. However, I'd rather just use the original version plugin and pair that with native Gradle features.

This plugin seems like a nonstandard solution to something that Gradle natively supports. Nonstandard solutions like this that claim to be THE solution are not good for the community in my opinion. It'd be better if the community was on the same page concerning our build tools. I'd suggest adding a disclaimer that this plugin could be mostly replaced by native Gradle features.

**Comment by fkorotkov** [comment]
This plugin was a way to solve the following issue: imagine you have three subproject: `:services:A`,  `:services:B` and  `:services:C`. Only service A and C are GRPC services and depend on `io.grpc:*` dependencies. You define `io.grpc:grpc-core` version only once and can use them in both projects (service B doesn't need it so you proposal with *allprojects* doesn't work). I don't think Maven BOM solves such issue. it helps with transitive dependencies though but doesn't help within your big project.

As far as I know there is no such native support in Gradle. Plus this plugin can do auto-upgrade of the version with `updateLibraries` task.
